### ISSUE TITLE
Problem with document.activeElement

### ISSUE THREAD

**Issue by Klemo1997** [PacktPublishing/Mastering-React-Test-Driven-Development#21]
In the section named `Focusing the prompt` the `document.activeElement` didnt work for me (I m using jest `^27.0.6`  with dependency jest-environment-jsdom `27.0.6` ) meaning it remained set to document body.

The solution was attaching this code in createContainer function:

```js
export const createContainer = () => {
    const container = document.createElement('div')

    // Add this line here
    document.body.appendChild(container)

    ...
}
```

So basically just attaching container to the body helped me to solve this issue. Hope it will help someone with same problem.

**Comment by dirv** [comment]
Hi @Klemo1997. I just spent some time confirming the issue and your solution, which works great! I'll make sure Packt update the errata. Thank you very much.

**Comment by JosephA-packt** [comment]
The Errata has been updated on the repository @Klemo1997 @dirv and hence closing the issue.
