### ISSUE TITLE
Update for React 18

### ISSUE THREAD

**Issue by dung-phan** [PacktPublishing/Mastering-React-Test-Driven-Development#29]
Hi, I'm aware that there will be a second edition coming soon but in the meantime, I'm struggling to get the first test working with [createRoot](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis), as this doesn't seem to work: 

`it('renders the customer first name', () => {`
        `const customer = { firstName: 'Ashley'}`
        `const container = document.createElement('div')`
         `const root = createRoot(container)`
        `root.render(<Appointment customer={customer} />)`
        `expect(container.textContent).toMatch('Ashley')`
    `})`
    
`container.textContent` ends up returning an empty string. Any suggestion what's wrong here? Thank you in advance. I've been enjoying the book so far.

**Comment by dirv** [comment]
Hi @dung-phan thanks for getting in touch. 

Firstly --- the issue with your code is that with React 18 you now need to wrap `render` in a call to `act`.

The second edition is indeed coming soon. All the code samples are already online here:

https://github.com/PacktPublishing/Mastering-React-Test-Driven-Development-Second-Edition

The organisation is pretty different, and the code is fairly different from the first edition but chapter 1 is roughly the same. This file should help you:

https://github.com/PacktPublishing/Mastering-React-Test-Driven-Development-Second-Edition/blob/main/Chapter01/Complete/test/Appointment.test.js

Hope that helps.

**Comment by dung-phan** [comment]
Thank you @dirv for a swift response. That's indeed what I need.
