### ISSUE TITLE
is it correct to write "await ReactTestUtils.Simulate.submit()" ?

### ISSUE THREAD

**Issue by cxc421** [PacktPublishing/Mastering-React-Test-Driven-Development#3]
Hi @dirv , [in chapter 2](https://github.com/PacktPublishing/Mastering-React-Test-Driven-Development/blob/eb9b9a2439a3f200d235345a14b07210514291c6/appointments/test/CustomerForm.test.js#L65)
```js
  it('saves new first name when submitted', async () => {
    expect.hasAssertions();
    render(
      <CustomerForm
        firstName="Ashley"
        onSubmit={({ firstName }) =>
          expect(firstName).toEqual('Jamie')
        }
      />
    );
    await ReactTestUtils.Simulate.change(firstNameField(), {
      target: { value: 'Jamie' }
    });
    await ReactTestUtils.Simulate.submit(form('customer'));
  });
```

I noticed that neither `ReactTestUtils.Simulate.change()` nor `ReactTestUtils.Simulate.submit()` would return `Promise`, so I tried to remove async / await and the test still passed.

```js
  it('saves new first name when submitted', () => {
    expect.hasAssertions();
    render(
      <CustomerForm
        firstName="Ashley"
        onSubmit={({ firstName }) =>
          expect(firstName).toEqual('Jamie')
        }
      />
    );
    ReactTestUtils.Simulate.change(firstNameField(), {
      target: { value: 'Jamie' }
    });
    ReactTestUtils.Simulate.submit(form('customer'));
  });
```
Is it correct to remove async / await?

**Comment by dirv** [comment]
Hi, yes, you’re correct. The code listings are in error. Thanks for pointing this out--I’ll forward to the editors and I’ll get the codebase updated soon.

**Comment by ManikandanKurup-Packt** [comment]
@dirv Hi, can we close this issue if it has been resolved?

**Comment by ManikandanKurup-Packt** [comment]
Hi @dirv 
can we close this issue?

**Comment by ManikandanKurup-Packt** [comment]
@cxc421 
The codes have been updated by the author. There shouldn't be an issue now. 
Please reopen if the issue still persists.
