### ISSUE TITLE
Open index.html in your browser but there's no server?

### ISSUE THREAD

**Issue by twocs** [PacktPublishing/Mastering-React-Test-Driven-Development#4]
I was confused by this sentence at the end of Chapter 1.

> Open index.html in your browser and behold your creation:

I was wondering where my server was and how to open this file. I was unable to open localhost/index.html (because there is not a web server launched by running `npm run build `even after adding `"build": "webpack --watch --progress"` to package.json.

I looked at the code repository and saw there was a folder for "server" but when I looked at the chapter-1-exercises tag, there was no mention of "server".

Finally after some fruitless attempts at getting it to go with `npm start` and other useless commands, it dawned on me that I could open the file itself to see how the browser would render it. In Visual Studio Code, I had to right click the file itself, get its absolute path, and then paste that full path into a browser search bar to open it in the browser without any server.

Other than that confusion, Chapter 1 was quite good. There was a minor dilemma regarding the "There are no appointments scheduled for today." text that disappeared from some of the partial code but that's easy to crosscheck with the repository.

**Comment by dirv** [comment]
Thanks for the feedback @twocs, it’s very helpful. I‘ll update the readme to hopefully make this clearer. Please do let me know if you have any other struggles with the book.
