### ISSUE TITLE
Missing tags for exercises for chapter 6 and 8

### ISSUE THREAD

**Issue by pnowak** [PacktPublishing/Mastering-React-Test-Driven-Development#5]
Hi @dirv

First of all a great book. 
Thank you.

I try to resolve the exercises for chapter 6. Unfortunately, `tags/chapter-6-exercises` doesn't work.
I try this same for chapter 8 and it's the same.

Am I missing something?

**Comment by dirv** [comment]
Hi @pnowak 

Thanks for bringing this to my attention. You’re not missing anything: the `chapter-6-exercises` tag isn’t in the repo and it’s not even mentioned in the book. Sorry about that.

I've had a quick look through the commit history and I'm 99% sure it’s commit `e4d81813b2709edc3e97b96818b65aa874e6dec1`.

I’ll push a tag for this at some point during the week, and have this added to the errata for the book.

As for chapter 8, you can actually use the tag for the subsequent chapter, which is `relay-environment`. It seems like I never got round to implementing the exercises for that chapter myself 😳 I’ll put that on my todo list.

Thanks again for pointing these issues out. If you spot any other issues please let me know so I can get to work on fixing them.

**Comment by pnowak** [comment]
Thank you for your answer. Now I know that I not missing anything. 

Since you have already mentioned to further checking I did it and unfortunately found another issue. In chapter 11 is also missing tags. 

Generally, it is no big deal. But I would like to see your solution. Especially in chapter 8 and 11 ;)

So thanks again for your work and book.

**Comment by dirv** [comment]
I’ve been looking into Chapter 11 a little and I think the first two exercises are done (in commits `b9a3dbb517161641d841c465bcaff1cc7a97b786` and `103a11c39f58d6a600cc6543f7a078215af9883e`). Let me know if you disagree with that. The other two exercises are:

* Loading an existing script (for example, on startup) will take a long time to animate all instructions, and so will pasting in code snippets. How would you modify the system to fast-forward animation in these circumstances?
* How does the undo and redo feature affect animation?

There at least a few different solutions to the first problem. I think what I’d try to do is block animation except in the case where only one command has been added. If multiple commands have been added then don’t run any animations. I’ll give this solution a go.

As for the second question, I’m guessing the answer is that it’s not pretty :) I will see if I can come up with a satisfactory solution to that, too.

I will go through each chapter and ensure the repo has tags for the start and end of each exercise sections. I’ll make sure that Packt are aware of that too.

**Comment by pnowak** [comment]
If it comes to commits I agree with you. 
This is correct commits for the first two exercises.

Thank you for that and clues.
